### ISSUE TITLE
Getting Started - Build for R Car Starter Kit gen3 board

### ISSUE THREAD

**Issue by Ramsheads** [automotive-grade-linux/docs-agl#110]
Hi.

I think that u-boot params below are wrong in agl eel.

[Getting Started - Build for R Car Starter Kit gen3 board](http://docs.automotivelinux.org/docs/getting_started/en/dev/reference/machines/R-Car-Starter-Kit-gen3.html#configure-u-boot-parameters)

- On web sites
setenv bootargs console=ttySC0,115200 root=/dev/mmcblk1p1 rootwait ro rootfstype=ext4

- I think it is correct
setenv bootargs console=ttySC0,115200 root=/dev/mmcblk0p1 rootwait ro rootfstype=ext4

- On web sites
setenv load_dtb ext4load mmc 0:1 0x48000000 /boot/Image-r8a7795-es1-h3ulcb.dtb
setenv load_dtb ext4load mmc 0:1 0x48000000 /boot/Image-r8a7795-h3ulcb.dtb
setenv load_dtb ext4load mmc 0:1 0x48000000 /boot/Image-r8a7796-m3ulcb.dtb

- I think it is correct
setenv load_dtb ext4load mmc 0:1 0x48000000 /boot/r8a7795-es1-h3ulcb.dtb
setenv load_dtb ext4load mmc 0:1 0x48000000 /boot/r8a7795-h3ulcb.dtb
setenv load_dtb ext4load mmc 0:1 0x48000000 /boot/r8a7796-m3ulcb.dtb

Sorry, my poor English.
I'm glad if this misstake is fixed.

**Comment by itsN1X** [comment]
@Ramsheads 
1. The  `/dev/mmcblk1` can be the on board emmc card itself, whereas the `/dev/mmcblk0` is the slotted in sdhc card.
Thus, to boot `initrd` off the main core, it solely depends whther its a bbb with an emmc+sdhc option, or simple 3B with only sdhc option.
Since they've considered installation on the ren. porter i guess, the emmc module being pressent, `/dev/mmcblk1/`  consists of the payload.
Yes, by default unless mentioned we must prefer ` setenv bootargs console=ttySC0,115200 root=/dev/mmcblk0p1 rootwait ro rootfstype=ext4` as mentioned!

2. renaming/vcs error?

----

*edit
 1. << I meant devices with onboard storage for booting and optional extra storage would default to `/dev/mmcblk1` and the filesystem could be `/dev/mmcblk1` or `/dev/mmcblk0`.

**Comment by KZYSAKYM** [comment]
@itsN1X 
> 1. The `/dev/mmcblk1` can ...

Thanks!

> 2. renaming/vcs error?

Sorry, what's vcs?

I think those dtb files were renamed, maybe. 
When I booted AGL Dab on R-Car M3SK a year ago, I think `/boot/Image-r8a7796-m3ulcb.dtb` is correct.

I suggest that we change the descriptions of the documents (from `/boot/Image-...` to `/boot/r8a77...`) or we add the procudure of seeing the contents of `/boot` before booting.

> Oh,Sorry, I commented by my unusual account...

**Comment by itsN1X** [comment]
VCS==git, or so.
---
Yes, @KZYSAKYM !
1. Shall I initiate a pull request?
2. Changes incude:
 - [x] new identifier is `/dev/mmcblk0p1`.
 - [x] Implementing this: 
`mv Image-r8a7795-es1-h3ulcb.dtb r8a7795-es1-h3ulcb.dtb && mv Image-r8a7795-es1-h3ulcb.dtb r8a7795-es1-h3ulcb.dtb && mv Image-r8a7795-es1-m3ulcb.dtb r8a7795-es1-m3ulcb.dtb` inside the `/boot` shall fix all this.
---
@KZYSAKYM @Ramsheads `Feedback`?

**Comment by KZYSAKYM** [comment]
@itsN1X 
> VCS==git, or so.
Thank you. I was not used to call git (etc...) vcs.

Ah... This issue is my first issue, so I don't know how to proceed after this. What should I do?
I agree your change.

> @KZYSAKYM @Ramsheads Feedback?
Yes.

**Comment by kooltux** [comment]
Please move this issue to jira.automotivelinux.org if needed. Thanks!
