### ISSUE TITLE
Terminal access for AGL

### ISSUE THREAD

**Issue by prp20** [automotive-grade-linux/docs-agl#114]
I'm running AGL Linux on Intel Minnowboard Max. Want to know how to access the terminal in AGL. I can now only access the UI. So would like some help in this regard. 

thanks in advance

**Comment by dominig** [comment]
The easiest is to use a serial cable and to connect with a serial console
emulator such as minicom.
Alternative is to ssh in the unit as root.

Obviously in the last option requires to know the up address allocated by
the dhcp.
Personally I run a second eth interface with a USB adaptor on my pc with a
dnsmask acting as shop server for that interface,  so it's easy to control
which up address is given to the Minnow.
There is no display of the up address in the AGL menus. There is an open
bug on that  topic. Contributions are welcome.

Dominig

On 30 Apr 2018 06:35, "Prasad PR" <notifications@github.com> wrote:

I'm running AGL Linux on Intel Minnowboard Max. Want to know how to access
the terminal in AGL. I can now only access the UI. So would like some help
in this regard.

thanks in advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/automotive-grade-linux/docs-agl/issues/114>, or mute
the thread
